routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (is_file(storage_path('.installed'))) {
        return redirect()->route('home');
    } else {
        return redirect()->route('install.overview');
    }
});

Route::get('links/{any}', function () {
    $package = request('package');
    abort_if(empty($package), 404);
    return redirect('https://play.google.com/store/apps/details?id=' . $package);
});

Route::redirect('clips', 'links/clips');

Route::get('install', 'InstallController@overview')->name('install.overview');
Route::get('install/configure', 'InstallController@configure')->name('install.configure');
Route::post('install/configure', 'InstallController@save');
Route::get('install/finalize', 'InstallController@finalize')->name('install.finalize');
Route::post('install/finalize', 'InstallController@run');

Auth::routes(['register' => false]);

Route::middleware(['auth', 'enabled', 'can:manage'])->group(function () {

    Route::get('home', 'HomeController@index')->name('home');

    Route::group(['layout' => 'layouts.panel'], function () {

        Route::livewire('config', 'config-update')
            ->middleware(['can:administer', 'password.confirm'])
            ->name('config.update');

        Route::livewire('users', 'user-index')->name('users.index');
        Route::livewire('users/create', 'user-create')->name('users.create');
        Route::livewire('users/{user}', 'user-show')->name('users.show');
        Route::livewire('users/{user}/update', 'user-update')->name('users.update');
        Route::livewire('users/{user}/destroy', 'user-destroy')->name('users.destroy');

        Route::prefix('videos')->group(function () {

            Route::livewire('clip-sections', 'clip-section-index')->name('clip-sections.index');
            Route::livewire('clip-sections/create', 'clip-section-create')->name('clip-sections.create');
            Route::livewire('clip-sections/{section}', 'clip-section-show')->name('clip-sections.show');
            Route::livewire('clip-sections/{section}/update', 'clip-section-update')->name('clip-sections.update');
            Route::livewire('clip-sections/{section}/destroy', 'clip-section-destroy')->name('clip-sections.destroy');

            Route::livewire('clips', 'clip-index')->name('clips.index');
            Route::livewire('clips/create', 'clip-create')->name('clips.create');
            Route::livewire('clips/{clip}', 'clip-show')->name('clips.show');
            Route::livewire('clips/{clip}/update', 'clip-update')->name('clips.update');
            Route::livewire('clips/{clip}/destroy', 'clip-destroy')->name('clips.destroy');
        });

        Route::prefix('news')->group(function () {

            Route::livewire('article-sections', 'article-section-index')->name('article-sections.index');
            Route::livewire('article-sections/create', 'article-section-create')->name('article-sections.create');
            Route::livewire('article-sections/{section}', 'article-section-show')->name('article-sections.show');
            Route::livewire('article-sections/{section}/update', 'article-section-update')->name('article-sections.update');
            Route::livewire('article-sections/{section}/destroy', 'article-section-destroy')->name('article-sections.destroy');

            Route::livewire('articles', 'article-index')->name('articles.index');
            Route::livewire('articles/create', 'article-create')->name('articles.create');
            Route::livewire('articles/{article}', 'article-show')->name('articles.show');
            Route::livewire('articles/{article}/update', 'article-update')->name('articles.update');
            Route::livewire('articles/{article}/destroy', 'article-destroy')->name('articles.destroy');
        });

        Route::prefix('music')->group(function () {

            Route::livewire('song-sections', 'song-section-index')->name('song-sections.index');
            Route::livewire('song-sections/create', 'song-section-create')->name('song-sections.create');
            Route::livewire('song-sections/{section}', 'song-section-show')->name('song-sections.show');
            Route::livewire('song-sections/{section}/update', 'song-section-update')->name('song-sections.update');
            Route::livewire('song-sections/{section}/destroy', 'song-section-destroy')->name('song-sections.destroy');

            Route::livewire('songs', 'song-index')->name('songs.index');
            Route::livewire('songs/create', 'song-create')->name('songs.create');
            Route::livewire('songs/{song}', 'song-show')->name('songs.show');
            Route::livewire('songs/{song}/update', 'song-update')->name('songs.update');
            Route::livewire('songs/{song}/destroy', 'song-destroy')->name('songs.destroy');
        });

        Route::prefix('engagement')->group(function () {

            Route::livewire('suggestions', 'suggestion-index')->name('suggestions.index');
            Route::livewire('suggestions/{suggestion}', 'suggestion-show')->name('suggestions.show');
            Route::livewire('suggestions/{suggestion}/update', 'suggestion-update')->name('suggestions.update');
            Route::livewire('suggestions/{suggestion}/destroy', 'suggestion-destroy')->name('suggestions.destroy');

            Route::livewire('challenges', 'challenge-index')->name('challenges.index');
            Route::livewire('challenges/create', 'challenge-create')->name('challenges.create');
            Route::livewire('challenges/{challenge}', 'challenge-show')->name('challenges.show');
            Route::livewire('challenges/{challenge}/update', 'challenge-update')->name('challenges.update');
            Route::livewire('challenges/{challenge}/destroy', 'challenge-destroy')->name('challenges.destroy');

            Route::livewire('sticker-sections', 'sticker-section-index')->name('sticker-sections.index');
            Route::livewire('sticker-sections/create', 'sticker-section-create')->name('sticker-sections.create');
            Route::livewire('sticker-sections/{section}', 'sticker-section-show')->name('sticker-sections.show');
            Route::livewire('sticker-sections/{section}/update', 'sticker-section-update')->name('sticker-sections.update');
            Route::livewire('sticker-sections/{section}/destroy', 'sticker-section-destroy')->name('sticker-sections.destroy');

            Route::livewire('stickers/{sticker}/destroy', 'sticker-destroy')->name('stickers.destroy');

            Route::livewire('comments', 'comment-index')->name('comments.index');
            Route::livewire('comments/{comment}', 'comment-show')->name('comments.show');
            Route::livewire('comments/{comment}/destroy', 'comment-destroy')->name('comments.destroy');

            Route::livewire('reports', 'report-index')->name('reports.index');
            Route::livewire('reports/{report}', 'report-show')->name('reports.show');
            Route::livewire('reports/{report}/update', 'report-update')->name('reports.update');
            Route::livewire('reports/{report}/destroy', 'report-destroy')->name('reports.destroy');
        });

        Route::prefix('rewards')->group(function () {

            Route::livewire('verifications', 'verification-index')->name('verifications.index');
            Route::livewire('verifications/{verification}', 'verification-show')->name('verifications.show');
            Route::livewire('verifications/{verification}/update', 'verification-update')->name('verifications.update');
            Route::livewire('verifications/{verification}/destroy', 'verification-destroy')->name('verifications.destroy');
        });

        Route::prefix('marketing')->group(function () {

            Route::livewire('promotions', 'promotion-index')->name('promotions.index');
            Route::livewire('promotions/create', 'promotion-create')->name('promotions.create');
            Route::livewire('promotions/{promotion}', 'promotion-show')->name('promotions.show');
            Route::livewire('promotions/{promotion}/update', 'promotion-update')->name('promotions.update');
            Route::livewire('promotions/{promotion}/destroy', 'promotion-destroy')->name('promotions.destroy');

            Route::livewire('advertisements', 'advertisement-index')->name('advertisements.index');
            Route::livewire('advertisements/create', 'advertisement-create')->name('advertisements.create');
            Route::livewire('advertisements/{advertisement}', 'advertisement-show')->name('advertisements.show');
            Route::livewire('advertisements/{advertisement}/update', 'advertisement-update')->name('advertisements.update');
            Route::livewire('advertisements/{advertisement}/destroy', 'advertisement-destroy')->name('advertisements.destroy');
        });

        Route::prefix('notifications')->group(function () {

            Route::livewire('notification-templates', 'notification-template-index')->name('notification-templates.index');
            Route::livewire('notification-templates/create', 'notification-template-create')->name('notification-templates.create');
            Route::livewire('notification-templates/{template}', 'notification-template-show')->name('notification-templates.show');
            Route::livewire('notification-templates/{template}/update', 'notification-template-update')->name('notification-templates.update');

app/User.php
<?php

namespace App;

use BeyondCode\Comments\Contracts\Commentator;
use Cmgmyr\Messenger\Traits\Messagable;
use CyrildeWit\EloquentViewable\View;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;
use Overtrue\LaravelFavorite\Traits\Favoriter;
use Overtrue\LaravelFollow\Followable;
use Overtrue\LaravelLike\Like;
use Overtrue\LaravelLike\Traits\Liker;
use Spatie\Activitylog\Contracts\Activity;
use Spatie\Activitylog\Traits\LogsActivity;

class User extends Authenticatable implements Commentator
{
    use BlockUnblock, Followable, HasApiTokens, Liker, Favoriter, LogsActivity, Notifiable, Messagable;

    protected static $logFillable = true;
    protected static $logOnlyDirty = true;

    protected $casts = [
        'enabled' => 'boolean',
        'verified' => 'boolean',
        'links' => 'array',
    ];

    protected $dates = [
        'email_verified_at',
    ];

    protected $fillable = [
        'name', 'email', 'password', 'role', 'enabled', 'username', 'bio', 'verified', 'photo', 'phone', 'facebook_id',
        'google_id', 'links', 'location', 'latitude', 'longitude',
    ];

    protected $hidden = [
        'password', 'remember_token', 'facebook_id', 'google_id',
    ];

    public function clips()
    {
        return $this->hasMany(Clip::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function devices()
    {
        return $this->hasMany(Device::class);
    }

    public function getDescriptionForEvent(string $event): string
    {
        return sprintf('User "%s" was %s.', Str::lower($this->name), $event);
    }

    public function getLikesTotalAttribute()
    {
        return Cache::remember("user_{$this->id}_likes", now()->addHour(), function () {
            return Like::query()
                ->whereHasMorph('likeable', Clip::class, function (Builder $query) {
                    $query->whereHas('user', function (Builder $query) {
                        $query->whereKey($this->id);
                    });
                })
                ->count();
        });
    }

    public function getViewsTotalAttribute()
    {
        return Cache::remember("user_{$this->id}_views", now()->addHour(), function () {
            return View::query()
                ->whereHasMorph('viewable', Clip::class, function (Builder $query) {
                    $query->whereHas('user', function (Builder $query) {
                        $query->whereKey($this->id);
                    });
                })
                ->count();
        });
    }

    public function needsCommentApproval($model): bool
    {
        return false;
    }

    public function reportedReport()
    {
        return $this->hasMany(Report::class);
    }

    public function reports()
    {
        return $this->morphMany(Report::class, 'subject');
    }

    public function suggestion()
    {
        return $this->hasOne(Suggestion::class);
    }

    public function tapActivity(Activity $activity, string $event)
    {
        if ($properties = $activity->changes()) {
            foreach ($this->hidden as $attr) {
                if (Arr::has($properties, "attributes.$attr")) {
                    $attributes = $properties->get('attributes');
                    $attributes[$attr] = '*hidden*';
                    $properties->put('attributes', $attributes);
                }
                if (Arr::has($properties, "old.$attr")) {
                    $old = $properties->get('old');
                    $old[$attr] = '*hidden*';
                    $properties->put('old', $old);
                }
            }
            $activity->properties = $properties;
        }
    }

    public function verifications()
    {
        return $this->hasMany(Verification::class);
    }
}

app/Http/Livewire/AdvertisementDestroy.php
<?php

namespace App\Http\Livewire;

use App\Advertisement;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class AdvertisementDestroy extends Component
{
    use AuthorizesRequests;

    public $advertisement;

    public function mount(Advertisement $advertisement)
    {
        $this->advertisement = $advertisement;
    }

    public function render()
    {
        return view('livewire.advertisement-destroy');
    }

    public function destroy()
    {
        $this->authorize('administer');
        $this->advertisement->delete();
        session()->flash('info', __('Advertisement #:id has been deleted.', ['id' => $this->advertisement->id]));
        return redirect()->route('advertisements.index');
    }
}

app/Http/Livewire/AdvertisementIndex.php
<?php

namespace App\Http\Livewire;

use App\Advertisement;
use Illuminate\Database\Eloquent\Builder;
use Livewire\Component;
use Livewire\WithPagination;

class AdvertisementIndex extends Component
{
    use WithPagination;

    public $search;

    public $length;

    public function mount()
    {
        $this->length = '10';
    }

    public function updatingLength()
    {
        $this->resetPage();
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $query = Advertisement::query();
        if ($this->search) {
            $query->where(function (Builder $query) {
                $query->where('type', 'like', "%$this->search%")
                    ->orWhere('location', 'like', "%$this->search%")
                    ->orWhere('network', 'like', "%$this->search%")
                    ->orWhere('link', 'like', "%$this->search%");
            });
        }

        $advertisements = $query->latest()->paginate($this->length);
        return view('livewire.advertisement-index', compact('advertisements'));
    }
}

app/Http/Livewire/AdvertisementShow.php
<?php

namespace App\Http\Livewire;

use App\Advertisement;
use Livewire\Component;

class AdvertisementShow extends Component
{
    public $advertisement;

    public function mount(Advertisement $advertisement)
    {
        $this->advertisement = $advertisement;
    }

    public function render()
    {
        $activities = $this->advertisement->activities()->latest()->paginate();
        return view('livewire.advertisement-show', compact('activities'));
    }
}

app/Http/Livewire/ArticleDestroy.php
<?php

namespace App\Http\Livewire;

use App\Article;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class ArticleDestroy extends Component
{
    use AuthorizesRequests;

    public $article;

    public function mount(Article $article)
    {
        $this->article = $article;
    }

    public function render()
    {
        return view('livewire.article-destroy');
    }

    public function destroy()
    {
        $this->authorize('administer');
        $this->article->sections()->detach();
        $this->article->delete();
        session()->flash('info', __('Article :title has been deleted.', ['title' => $this->article->title_short]));
        return redirect()->route('articles.index');
    }
}

resources/views/livewire/statistics-views.blade.php
<div class="card shadow-sm">
    <div class="card-body">
        <div class="spinner-border spinner-border-sm float-right" role="status" wire:loading>
            <span class="sr-only">{{ __('Loading') }}&hellip;</span>
        </div>
        <h5 class="card-title text-primary">{{ __('Views') }}</h5>
        <p class="card-text">{{ __('Below are the number of views on clips shown comparatively.') }}</p>
    </div>
    <div class="table-responsive">
        <table class="table mb-0">
            <tbody>
            <tr>
                <th class="bg-light w-50">
                    @if ($mode === '1H')
                        {{ __('This hour') }}
                    @elseif ($mode === '1D')
                        {{ __('Today') }}
                    @elseif ($mode === '1W')
                        {{ __('This week') }}
                    @elseif ($mode === '1M')
                        {{ __('This month') }}
                    @endif
                </th>
                <td class="w-50">{{ $current }}</td>
            </tr>
            <tr>
                <th class="bg-light w-50">
                    @if ($mode === '1H')
                        {{ __('Last hour') }}
                    @elseif ($mode === '1D')
                        {{ __('Yesterday') }}
                    @elseif ($mode === '1W')
                        {{ __('Last week') }}
                    @elseif ($mode === '1M')
                        {{ __('Last month') }}
                    @endif
                </th>
                <td class="w-50">{{ $previous }}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="card-body border-top">
        <div class="btn-group btn-group-sm" role="group">
            <button type="button" class="btn btn-outline-dark @if ($mode === '1H') active @endif" wire:click="update('1H')" wire:loading.attr="disabled">{{ __('1H') }}</button>
            <button type="button" class="btn btn-outline-dark @if ($mode === '1D') active @endif" wire:click="update('1D')" wire:loading.attr="disabled">{{ __('1D') }}</button>
            <button type="button" class="btn btn-outline-dark @if ($mode === '1W') active @endif" wire:click="update('1W')" wire:loading.attr="disabled">{{ __('1W') }}</button>
            <button type="button" class="btn btn-outline-dark @if ($mode === '1M') active @endif" wire:click="update('1M')" wire:loading.attr="disabled">{{ __('1M') }}</button>
        </div>
    </div>
    <div class="card-footer">
        <small>
            <span class="text-muted">{{ __('Last updated on') }}</span> {{ now()->format('H:i') }}
        </small>
    </div>
</div>

resources/views/livewire/user-show.blade.php
@section('meta')
    <title>{{ __('Users') }} &raquo; {{ $user->name }} - {{ __('Backend') }} | {{ config('app.name') }}</title>
@endsection

@section('body')
    @livewire('send-notification', ['user' => $user->id])
    @parent
@endsection

<div>
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url('/') }}">{{ config('app.name') }}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('users.index') }}">{{ __('Users') }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ $user->name }}</li>
            </ol>
        </nav>
        <div class="btn-toolbar mb-3">
            <a class="btn btn-outline-dark" href="{{ route('users.index') }}">
                <i class="fas fa-arrow-left mr-1"></i> {{ __('Users') }}
            </a>
            <button class="btn btn-warning ml-auto" data-toggle="modal" data-target="#modal-notification">
                <i class="fas fa-bullhorn mr-1"></i> {{ __('Notification') }}
            </button>
            @if (!$user->can('manage') || Gate::check('administer'))
                <a class="btn btn-info ml-1" href="{{ route('users.update', $user) }}">
                    <i class="fas fa-feather mr-1"></i> {{ __('Edit') }}
                </a>
            @endif
            @can('administer')
                <a class="btn btn-danger ml-1" href="{{ route('users.destroy', $user) }}">
                    <i class="fas fa-trash mr-1"></i> {{ __('Delete') }}
                </a>
            @endcan
        </div>
        @include('partials.flash')
        <div class="row">
            <div class="col-md-6 col-lg-8">
                <div class="card shadow-sm mb-3 mb-md-0">
                    <div class="card-body">
                        <h5 class="card-title text-primary">{{ __('Details') }}</h5>
                        <p class="card-text">{{ __('See information about existing user here.') }}</p>
                    </div>
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <tbody>
                            <tr>
                                <th class="bg-light">{{ __('Name') }}</th>
                                <td class="w-100">{{ $user->name }}</td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Username') }}</th>
                                <td class="w-100">&commat;{{ $user->username }}</td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Email address') }}</th>
                                <td class="w-100">
                                    @if (config('fixtures.demo_mode'))
                                        <span class="text-muted">{{ __('Redacted in demo') }}</span>
                                    @elseif ($user->email)
                                        <a href="mailto:{{ $user->email }}">{{ $user->email }}</a>
                                    @else
                                        <span class="text-muted">{{ __('Empty') }}</span>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Phone number') }}</th>
                                <td class="w-100">
                                    @if (config('fixtures.demo_mode'))
                                        <span class="text-muted">{{ __('Redacted in demo') }}</span>
                                    @elseif ($user->phone)
                                        <a href="tel:{{ $user->phone }}">{{ $user->phone }}</a>
                                    @else
                                        <span class="text-muted">{{ __('Empty') }}</span>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Password') }}</th>
                                <td class="w-100 text-muted">&ast;&ast;&ast;&ast;&ast;</td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Role') }}</th>
                                <td class="w-100">
                                    @if ($user->role)
                                        {{ config('fixtures.user_roles.' . $user->role) }}
                                    @else
                                        <span class="text-muted">{{ __('None') }}</span>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Enabled?') }}</th>
                                <td class="w-100">
                                    @if ($user->enabled)
                                        <i class="fas fa-toggle-on mr-1 text-success"></i>
                                    @else
                                        <i class="fas fa-toggle-off mr-1 text-danger"></i>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light align-text-top">{{ __('Photo') }}</th>
                                <td class="w-100 text-wrap">
                                    @if ($user->photo)
                                        <a href="{{ Storage::cloud()->url($user->photo) }}" rel="noopener noreferrer" target="_blank">{{ $user->photo }}</a>
                                    @else
                                        <span class="text-muted">{{ __('Empty') }}</span>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light align-text-top">{{ __('Bio') }}</th>
                                <td class="w-100 text-wrap">
                                    @if ($user->bio)
                                        {{ $user->bio }}
                                    @else
                                        <span class="text-muted">{{ __('Empty') }}</span>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Verified?') }}</th>
                                <td class="w-100">
                                    @if ($user->verified)
                                        <i class="fas fa-toggle-on mr-1 text-success"></i>
                                    @else
                                        <i class="fas fa-toggle-off mr-1 text-danger"></i>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light align-text-top">{{ __('Links') }}</th>
                                <td class="w-100 text-wrap">
                                    @if ($user->links)
                                        @foreach($user->links as $link)
                                            <i class="fab fa-{{ $link['type'] }} text-{{ $link['type'] }} mr-1"></i>
                                            <a class="text-{{ $link['type'] }}" href="{{ $link['url'] }}" target="_blank">
                                                {{ config('fixtures.link_types.' . $link['type']) }}
                                            </a>
                                        @endforeach
                                    @else
                                        <span class="text-muted">{{ __('None') }}</span>
                                    @endif
                                </td>
                            </tr>
                            @if ($user->location)
                                <tr>
                                    <th class="bg-light">{{ __('Location') }}</th>
                                    <td class="w-100">
                                        <a href="http://maps.google.com/maps?q={{ $user->latitude }},{{ $user->longitude }}" rel="noopener noreferrer" target="_blank">
                                            {{ $user->location }}
                                        </a>
                                    </td>
                                </tr>
                            @endif
                            <tr>
                                <th class="bg-light">{{ __('Clips') }}</th>
                                <td class="w-100">{{ $user->clips()->count() }}</td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Views') }}</th>
                                <td class="w-100">{{ $user->views_total }}</td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Likes') }}</th>
                                <td class="w-100">{{ $user->likes_total }}</td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Followers') }}</th>
                                <td class="w-100">{{ $user->followers()->count() }}</td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Followings') }}</th>
                                <td class="w-100">{{ $user->followings()->count() }}</td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Favorites') }}</th>
                                <td class="w-100">{{ $user->favorites()->count() }}</td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Reports') }}</th>
                                <td class="w-100">{{ $user->reports()->count() }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <span class="text-muted">{{ __('Created at') }}</span> {{ $user->created_at->format('d/m/Y H:i') }}
                        <span class="d-none d-md-inline">
                            &bull;
                            <span class="text-muted">{{ __('Updated at') }}</span> {{ $user->updated_at->format('d/m/Y H:i') }}
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                @include('partials.activity_logs')
            </div>
        </div>

    </div>
</div>