backup/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (is_file(storage_path('.installed'))) {
        return redirect()->route('home');
    } else {
        return redirect()->route('install.overview');
    }
});

Route::prefix('links')->group(function () {

    $redirect = function () {
        $package = request('package');
        abort_if(empty($package), 404);
        return redirect('https://play.google.com/store/apps/details?id=' . $package);
    };

    Route::get('clips', $redirect);
    Route::get('users', $redirect);
});

Route::redirect('clips', 'links/clips');

Route::get('install', 'InstallController@overview')->name('install.overview');
Route::get('install/configure', 'InstallController@configure')->name('install.configure');
Route::post('install/configure', 'InstallController@save');
Route::get('install/finalize', 'InstallController@finalize')->name('install.finalize');
Route::post('install/finalize', 'InstallController@run');

Auth::routes(['register' => false]);

Route::middleware(['auth', 'enabled', 'can:manage'])->group(function () {

    Route::get('home', 'HomeController@index')->name('home');

    Route::group(['layout' => 'layouts.panel'], function () {

        Route::livewire('users', 'user-index')->name('users.index');
        Route::livewire('users/create', 'user-create')->name('users.create');
        Route::livewire('users/{user}', 'user-show')->name('users.show');
        Route::livewire('users/{user}/update', 'user-update')->name('users.update');
        Route::livewire('users/{user}/destroy', 'user-destroy')->name('users.destroy');

        Route::prefix('videos')->group(function () {

            Route::livewire('clip-sections', 'clip-section-index')->name('clip-sections.index');
            Route::livewire('clip-sections/create', 'clip-section-create')->name('clip-sections.create');
            Route::livewire('clip-sections/{section}', 'clip-section-show')->name('clip-sections.show');
            Route::livewire('clip-sections/{section}/update', 'clip-section-update')->name('clip-sections.update');
            Route::livewire('clip-sections/{section}/destroy', 'clip-section-destroy')->name('clip-sections.destroy');

            Route::livewire('clips', 'clip-index')->name('clips.index');
            Route::livewire('clips/{clip}', 'clip-show')->name('clips.show');
            Route::livewire('clips/{clip}/update', 'clip-update')->name('clips.update');
            Route::livewire('clips/{clip}/destroy', 'clip-destroy')->name('clips.destroy');
        });

        Route::prefix('news')->group(function () {

            Route::livewire('article-sections', 'article-section-index')->name('article-sections.index');
            Route::livewire('article-sections/create', 'article-section-create')->name('article-sections.create');
            Route::livewire('article-sections/{section}', 'article-section-show')->name('article-sections.show');
            Route::livewire('article-sections/{section}/update', 'article-section-update')->name('article-sections.update');
            Route::livewire('article-sections/{section}/destroy', 'article-section-destroy')->name('article-sections.destroy');

            Route::livewire('articles', 'article-index')->name('articles.index');
            Route::livewire('articles/create', 'article-create')->name('articles.create');
            Route::livewire('articles/{article}', 'article-show')->name('articles.show');
            Route::livewire('articles/{article}/update', 'article-update')->name('articles.update');
            Route::livewire('articles/{article}/destroy', 'article-destroy')->name('articles.destroy');
        });

        Route::prefix('music')->group(function () {

            Route::livewire('song-sections', 'song-section-index')->name('song-sections.index');
            Route::livewire('song-sections/create', 'song-section-create')->name('song-sections.create');
            Route::livewire('song-sections/{section}', 'song-section-show')->name('song-sections.show');
            Route::livewire('song-sections/{section}/update', 'song-section-update')->name('song-sections.update');
            Route::livewire('song-sections/{section}/destroy', 'song-section-destroy')->name('song-sections.destroy');

            Route::livewire('songs', 'song-index')->name('songs.index');
            Route::livewire('songs/create', 'song-create')->name('songs.create');
            Route::livewire('songs/{song}', 'song-show')->name('songs.show');
            Route::livewire('songs/{song}/update', 'song-update')->name('songs.update');
            Route::livewire('songs/{song}/destroy', 'song-destroy')->name('songs.destroy');
        });

        Route::prefix('engagement')->group(function () {

            Route::livewire('suggestions', 'suggestion-index')->name('suggestions.index');
            Route::livewire('suggestions/{suggestion}', 'suggestion-show')->name('suggestions.show');
            Route::livewire('suggestions/{suggestion}/update', 'suggestion-update')->name('suggestions.update');
            Route::livewire('suggestions/{suggestion}/destroy', 'suggestion-destroy')->name('suggestions.destroy');

            Route::livewire('challenges', 'challenge-index')->name('challenges.index');
            Route::livewire('challenges/create', 'challenge-create')->name('challenges.create');
            Route::livewire('challenges/{challenge}', 'challenge-show')->name('challenges.show');
            Route::livewire('challenges/{challenge}/update', 'challenge-update')->name('challenges.update');
            Route::livewire('challenges/{challenge}/destroy', 'challenge-destroy')->name('challenges.destroy');

            Route::livewire('sticker-sections', 'sticker-section-index')->name('sticker-sections.index');
            Route::livewire('sticker-sections/create', 'sticker-section-create')->name('sticker-sections.create');
            Route::livewire('sticker-sections/{section}', 'sticker-section-show')->name('sticker-sections.show');
            Route::livewire('sticker-sections/{section}/update', 'sticker-section-update')->name('sticker-sections.update');
            Route::livewire('sticker-sections/{section}/destroy', 'sticker-section-destroy')->name('sticker-sections.destroy');

            Route::livewire('stickers/{sticker}/destroy', 'sticker-destroy')->name('stickers.destroy');

            Route::livewire('comments', 'comment-index')->name('comments.index');
            Route::livewire('comments/{comment}', 'comment-show')->name('comments.show');
            Route::livewire('comments/{comment}/destroy', 'comment-destroy')->name('comments.destroy');

            Route::livewire('reports', 'report-index')->name('reports.index');
            Route::livewire('reports/{report}', 'report-show')->name('reports.show');
            Route::livewire('reports/{report}/update', 'report-update')->name('reports.update');
            Route::livewire('reports/{report}/destroy', 'report-destroy')->name('reports.destroy');
        });

        Route::prefix('rewards')->group(function () {

            Route::livewire('verifications', 'verification-index')->name('verifications.index');
            Route::livewire('verifications/{verification}', 'verification-show')->name('verifications.show');
            Route::livewire('verifications/{verification}/update', 'verification-update')->name('verifications.update');
            Route::livewire('verifications/{verification}/destroy', 'verification-destroy')->name('verifications.destroy');
        });

        Route::prefix('marketing')->group(function () {

            Route::livewire('promotions', 'promotion-index')->name('promotions.index');
            Route::livewire('promotions/create', 'promotion-create')->name('promotions.create');
            Route::livewire('promotions/{promotion}', 'promotion-show')->name('promotions.show');
            Route::livewire('promotions/{promotion}/update', 'promotion-update')->name('promotions.update');
            Route::livewire('promotions/{promotion}/destroy', 'promotion-destroy')->name('promotions.destroy');

            Route::livewire('advertisements', 'advertisement-index')->name('advertisements.index');
            Route::livewire('advertisements/create', 'advertisement-create')->name('advertisements.create');
            Route::livewire('advertisements/{advertisement}', 'advertisement-show')->name('advertisements.show');
            Route::livewire('advertisements/{advertisement}/update', 'advertisement-update')->name('advertisements.update');
            Route::livewire('advertisements/{advertisement}/destroy', 'advertisement-destroy')->name('advertisements.destroy');
        });

        Route::prefix('notifications')->group(function () {

            Route::livewire('notification-templates', 'notification-template-index')->name('notification-templates.index');
            Route::livewire('notification-templates/create', 'notification-template-create')->name('notification-templates.create');
            Route::livewire('notification-templates/{template}', 'notification-template-show')->name('notification-templates.show');
            Route::livewire('notification-templates/{template}/update', 'notification-template-update')->name('notification-templates.update');
            Route::livewire('notification-templates/{template}/destroy', 'notification-template-destroy')->name('notification-templates.destroy');


backup/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Spatie\Activitylog\Contracts\Activity;
use Spatie\Activitylog\Traits\LogsActivity;

class Article extends Model
{
    use LogsActivity;

    protected static $logFillable = true;
    protected static $logOnlyDirty = true;

    protected $dates = [
        'published_at',
    ];

    protected $fillable = [
        'title', 'snippet', 'image', 'link', 'source', 'published_at', 'checksum',
    ];

    protected $hidden = [
        'checksum',
    ];

    public function sections()
    {
        return $this->belongsToMany(
            ArticleSection::class,
            'article_section_articles',
            'article_id',
            'section_id'
        );
    }

    public function getDescriptionForEvent(string $event): string
    {
        return sprintf('Article "%s" was %s.', Str::lower($this->title_short), $event);
    }

    public function getImageShortAttribute()
    {
        if (mb_strlen($this->image) > 20) {
            return mb_substr($this->image, 0, 20) . '…';
        }
        return $this->image;
    }

    public function getLinkShortAttribute()
    {
        if (mb_strlen($this->link) > 20) {
            return mb_substr($this->link, 0, 20) . '…';
        }
        return $this->link;
    }

    public function getTitleShortAttribute()
    {
        if (mb_strlen($this->title) > 20) {
            return mb_substr($this->title, 0, 20) . '…';
        }
        return $this->title;
    }

    public function tapActivity(Activity $activity, string $event)
    {
        if ($properties = $activity->changes()) {
            foreach ($this->hidden as $attr) {
                if (Arr::has($properties, "attributes.$attr")) {
                    $attributes = $properties->get('attributes');
                    $attributes[$attr] = '*hidden*';
                    $properties->put('attributes', $attributes);
                }
                if (Arr::has($properties, "old.$attr")) {
                    $old = $properties->get('old');
                    $old[$attr] = '*hidden*';
                    $properties->put('old', $old);
                }
            }
            $activity->properties = $properties;
        }
    }
}

backup/app/Clip.php
<?php

namespace App;

use BeyondCode\Comments\Traits\HasComments;
use CyrildeWit\EloquentViewable\Contracts\Viewable;
use CyrildeWit\EloquentViewable\InteractsWithViews;
use Illuminate\Database\Eloquent\Model;
use Overtrue\LaravelFavorite\Traits\Favoriteable;
use Overtrue\LaravelLike\Traits\Likeable;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Tags\HasTags;

class Clip extends Model implements Viewable
{
    use Favoriteable, HasComments, HasTags, InteractsWithViews, Likeable, LogsActivity;

    protected static $logFillable = true;
    protected static $logOnlyDirty = true;

    protected $casts = [
        'approved' => 'boolean',
        'private' => 'boolean',
        'comments' => 'boolean',
    ];

    protected $fillable = [
        'video', 'screenshot', 'preview', 'description', 'language', 'private', 'comments', 'duration', 'approved',
        'location', 'latitude', 'longitude',
    ];

    public function getDescriptionForEvent(string $event): string
    {
        return sprintf('Clip #%d was %s.', $this->id, $event);
    }

    public function getDescriptionShortAttribute()
    {
        if (mb_strlen($this->description) > 20) {
            return mb_substr($this->description, 0, 20) . '…';
        }
        return $this->description;
    }

    public function reports()
    {
        return $this->morphMany(Report::class, 'subject');
    }

    public function song()
    {
        return $this->belongsTo(Song::class);
    }

    public function sections()
    {
        return $this->belongsToMany(ClipSection::class,
            'clip_section_clips',
            'clip_id',
            'section_id'
        );
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

backup/app/Http/Livewire/AdvertisementDestroy.php
<?php

namespace App\Http\Livewire;

use App\Advertisement;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class AdvertisementDestroy extends Component
{
    use AuthorizesRequests;

    public $advertisement;

    public function mount(Advertisement $advertisement)
    {
        $this->advertisement = $advertisement;
    }

    public function render()
    {
        return view('livewire.advertisement-destroy');
    }

    public function destroy()
    {
        $this->authorize('administer');
        $this->advertisement->delete();
        session()->flash('info', __('Advertisement #:id has been deleted.', ['id' => $this->advertisement->id]));
        return redirect()->route('advertisements.index');
    }
}

backup/app/Http/Livewire/AdvertisementIndex.php
<?php

namespace App\Http\Livewire;

use App\Advertisement;
use Illuminate\Database\Eloquent\Builder;
use Livewire\Component;
use Livewire\WithPagination;

class AdvertisementIndex extends Component
{
    use WithPagination;

    public $search;

    public $length;

    public function mount()
    {
        $this->length = '10';
    }

    public function updatingLength()
    {
        $this->resetPage();
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $query = Advertisement::query();
        if ($this->search) {
            $query->where(function (Builder $query) {
                $query->where('type', 'like', "%$this->search%")
                    ->orWhere('location', 'like', "%$this->search%")
                    ->orWhere('network', 'like', "%$this->search%")
                    ->orWhere('link', 'like', "%$this->search%");
            });
        }

        $advertisements = $query->latest()->paginate($this->length);
        return view('livewire.advertisement-index', compact('advertisements'));
    }
}

backup/app/Http/Livewire/AdvertisementShow.php
<?php

namespace App\Http\Livewire;

use App\Advertisement;
use Livewire\Component;

class AdvertisementShow extends Component
{
    public $advertisement;

    public function mount(Advertisement $advertisement)
    {
        $this->advertisement = $advertisement;
    }

    public function render()
    {
        $activities = $this->advertisement->activities()->latest()->paginate();
        return view('livewire.advertisement-show', compact('activities'));
    }
}

backup/app/Http/Livewire/ArticleDestroy.php
<?php

namespace App\Http\Livewire;

use App\Article;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class ArticleDestroy extends Component
{
    use AuthorizesRequests;

    public $article;

    public function mount(Article $article)
    {
        $this->article = $article;
    }

    public function render()
    {
        return view('livewire.article-destroy');
    }

    public function destroy()
    {
        $this->authorize('administer');
        $this->article->sections()->detach();
        $this->article->delete();
        session()->flash('info', __('Article :title has been deleted.', ['title' => $this->article->title_short]));
        return redirect()->route('articles.index');
    }
}

backup/resources/views/livewire/article-show.blade.php
@section('meta')
    <title>{{ __('Articles') }} &raquo; {{ $article->title_short }} - {{ __('Backend') }} | {{ config('app.name') }}</title>
@endsection

<div>
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url('/') }}">{{ config('app.name') }}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('articles.index') }}">{{ __('Articles') }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ $article->title_short }}</li>
            </ol>
        </nav>
        <div class="btn-toolbar mb-3">
            <a class="btn btn-outline-dark" href="{{ route('articles.index') }}">
                <i class="fas fa-arrow-left mr-1"></i> {{ __('Articles') }}
            </a>
            <a class="btn btn-info ml-auto" href="{{ route('articles.update', $article) }}">
                <i class="fas fa-feather mr-1"></i> {{ __('Edit') }}
            </a>
            @can('administer')
                <a class="btn btn-danger ml-1" href="{{ route('articles.destroy', $article) }}">
                    <i class="fas fa-trash mr-1"></i> {{ __('Delete') }}
                </a>
            @endcan
        </div>
        @include('partials.flash')
        <div class="row">
            <div class="col-md-6 col-lg-8">
                <div class="card shadow-sm mb-3 mb-md-0">
                    <div class="card-body">
                        <h5 class="card-title text-primary">{{ __('Details') }}</h5>
                        <p class="card-text">{{ __('See information about existing article here.') }}</p>
                    </div>
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <tbody>
                            <tr>
                                <th class="bg-light">{{ __('Sections') }}</th>
                                <td class="w-100">
                                    @forelse ($article->sections as $section)
                                        <span class="badge badge-light">{{ $section->name }}</span>
                                    @empty
                                        <span class="text-muted">{{ __('Empty') }}</span>
                                    @endforelse
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light align-text-top">{{ __('Title') }}</th>
                                <td class="w-100 text-wrap">{{ $article->title }}</td>
                            </tr>
                            <tr>
                                <th class="bg-light align-text-top">{{ __('Snippet') }}</th>
                                <td class="w-100 text-wrap">{{ $article->snippet }}</td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Image') }}</th>
                                <td class="w-100">
                                    @if ($article->image)
                                        <a href="{{ $article->image }}" rel="noopener noreferrer" target="_blank">{{ $article->image_short }}</a>
                                    @else
                                        <span class="text-muted">{{ __('Empty') }}</span>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Link') }}</th>
                                <td class="w-100">
                                    <a href="{{ $article->link }}" rel="noopener noreferrer" target="_blank">{{ $article->link_short }}</a>
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Source') }}</th>
                                <td class="w-100">
                                    @if ($article->source)
                                        {{ $article->source }}
                                    @else
                                        <span class="text-muted">{{ __('Empty') }}</span>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th class="bg-light">{{ __('Published at') }}</th>
                                <td class="w-100">{{ $article->published_at->format('d/m/Y H:i') }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <span class="text-muted">{{ __('Created at') }}</span> {{ $article->created_at->format('d/m/Y H:i') }}
                        <span class="d-none d-md-inline">
                            &bull;
                            <span class="text-muted">{{ __('Updated at') }}</span> {{ $article->updated_at->format('d/m/Y H:i') }}
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                @include('partials.activity_logs')
            </div>
        </div>
    </div>
</div>

backup/resources/views/livewire/clip-index.blade.php
@section('meta')
    <title>{{ __('Clips') }} - {{ __('Backend') }} | {{ config('app.name') }}</title>
@endsection

<div>
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url('/') }}">{{ config('app.name') }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ __('Clips') }}</li>
            </ol>
        </nav>
        @include('partials.flash')
        <div class="card shadow-sm">
            <div class="card-body">
                <div class="spinner-border spinner-border-sm float-right" role="status" wire:loading>
                    <span class="sr-only">{{ __('Loading') }}&hellip;</span>
                </div>
                <h5 class="card-title text-primary">{{ __('Clips') }}</h5>
                <p class="card-text">{{ __('List and manage uploaded clips here.') }}</p>
            </div>
            <div class="card-body border-top">
                <div class="row">
                    <div class="col-sm-6 col-md-4 col-lg-3">
                        <div class="form-group mb-lg-0">
                            <label for="filter-search">{{ __('Search') }}</label>
                            <input id="filter-search" class="form-control" placeholder="{{ __('Enter user name or email') }}&hellip;" wire:model.debounce.500ms="search">
                        </div>
                    </div>
                    @php
                        $sections = App\ClipSection::query()->orderBy('order')->get();
                    @endphp
                    <div class="col-sm-6 col-md-4 col-lg-3">
                        <div class="form-group mb-lg-0">
                            <label for="filter-section">{{ __('Section') }}</label>
                            <select id="filter-section" class="form-control" wire:model="section">
                                <option value="">{{ __('Any') }}</option>
                                @foreach ($sections as $section)
                                    <option value="{{ $section->id }}">{{ $section->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-3">
                        <div class="form-group mb-sm-0">
                            <label for="filter-language">{{ __('Language') }}</label>
                            <select id="filter-language" class="form-control" wire:model="language">
                                <option value="">{{ __('Any') }}</option>
                                @foreach (config('fixtures.languages') as $code => $name)
                                    <option value="{{ $code }}">{{ $name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-3">
                        <div class="form-group mb-0">
                            <label for="filter-length">{{ __('Length') }}</label>
                            <select id="filter-length" class="form-control" wire:model="length">
                                <option value="10">10</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="100">100</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table mb-0">
                    <thead class="thead-light">
                    <tr>
                        <th>#</th>
                        <th></th>
                        <th>{{ __('Description') }}</th>
                        <th>{{ __('Language') }}</th>
                        <th>{{ __('Approved?') }}</th>
                        <th>{{ __('Created at') }}</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse ($clips as $clip)
                        <tr>
                            <td>{{ $clip->id }}</td>
                            <td>
                                <div class="text-hide img-screenshot rounded" style="background-image: url('{{ Storage::cloud()->url($clip->screenshot) }}')">&nbsp;</div>
                            </td>
                            <td>
                                @if ($clip->description)
                                    {{ $clip->description_short }}
                                @else
                                    <span class="text-muted">{{ __('Empty') }}</span>
                                @endif
                            </td>
                            <td>{{ config('fixtures.languages.' . $clip->language) }}</td>
                            <td>
                                @if ($clip->approved)
                                    <i class="fas fa-toggle-on mr-1 text-success"></i>
                                @else
                                    <i class="fas fa-toggle-off mr-1 text-danger"></i>
                                @endif
                            </td>
                            <td>{{ $clip->created_at->format('d/m/Y H:i:s') }}</td>
                            <td>
                                <a class="btn btn-outline-dark btn-sm" href="{{ route('clips.show', $clip) }}">
                                    <i class="fas fa-eye mr-1"></i> {{ __('Details') }}
                                </a>
                                <a class="btn btn-info btn-sm" href="{{ route('clips.update', $clip) }}">
                                    <i class="fas fa-feather mr-1"></i> {{ __('Edit') }}
                                </a>
                                @can('administer')
                                    <a class="btn btn-danger btn-sm" href="{{ route('clips.destroy', $clip) }}">
                                        <i class="fas fa-trash mr-1"></i> {{ __('Delete') }}
                                    </a>
                                @endcan
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td class="text-center text-muted" colspan="7">{{ __('Could not find any clips to show.') }}</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            @if ($clips->hasPages())
                <div class="card-body border-top">
                    {{ $clips->onEachSide(1)->links() }}
                </div>
            @endif
            <div class="card-body border-top">
                {{ __('Showing :from to :to of :total clips.', ['from' => $clips->firstItem() ?: 0, 'to' => $clips->lastItem() ?: 0, 'total' => $clips->total()]) }}
            </div>
        </div>
    </div>
</div>